version: "3"
services:
  gitlab-server:
    container_name: gitlab-server
    image: 'gitlab/gitlab-ce:15.8.0-ce.0'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '$GITLAB_URL'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/config:/etc/gitlab'
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$GITLAB_RUNNER/config:/etc/gitlab-runner'
    depends_on:
      gitlab-server:
        condition: service_healthy
    networks:
      - gitlab
networks:
  gitlab:
    name: gitlab-network
    driver: bridge
